(function exposeMountainData(root,factory){
  const data=factory();
  if(typeof module==='object'&&module.exports)module.exports=data;
  root.MountainPulseData=data;
})(typeof globalThis!=='undefined'?globalThis:this,function createMountainData(){
  const sourceMeta={
    operations:{mode:'simulation',available:true,quality:.65,freshness:.9,weight:3,label:'Scenario operations'},
    weather:{mode:'simulation',available:true,quality:.55,freshness:.8,weight:2,label:'Scenario weather'},
    webcam:{mode:'unavailable',available:false,quality:0,freshness:0,weight:1,label:'No camera connected'},
    movement:{mode:'simulation',available:true,quality:.6,freshness:.85,weight:2,label:'Scenario movement'},
    historical:{mode:'simulation',available:true,quality:.7,freshness:.75,weight:2,label:'Scenario history'}
  };

  const resorts={
    copper:{id:'copper',name:'Copper Mountain',state:'CO',pulse:{score:83,label:'Excellent right now',factors:{snow:89,crowds:76,lift_lines:84,terrain:91,wind:72}},conditions:{temperature_f:18,feels_like_f:9,snow_24h_in:7,wind:'W 12 mph',terrain_open_pct:93},crowds:{level:'moderate',trend:'moving east',contributors:1284},lifts:[{name:'Super Bee',area:'East Village',status:'open',wait_minutes:3,trend:'decreasing'},{name:'American Eagle',area:'Center Village',status:'open',wait_minutes:17,trend:'increasing rapidly'},{name:'Excelerator',area:'Upper mountain',status:'open',wait_minutes:4,trend:'steady'},{name:'Timberline Express',area:'West Village',status:'open',wait_minutes:11,trend:'increasing'},{name:'Three Bears',area:'Copper Bowl',status:'closed',wait_minutes:null,trend:'resort update 8m ago'}],runs:[{name:'Resolution',difficulty:'Black diamond',status:'open',surface:'groomed'},{name:'Spaulding Bowl',difficulty:'Expert',status:'caution',surface:'hard-packed choke'},{name:'Andy’s Encore',difficulty:'Blue',status:'open',surface:'groomed'},{name:'Three Bears terrain',difficulty:'Expert',status:'closed',surface:'patrol hold'}]},
    abasin:{id:'abasin',name:'Arapahoe Basin',state:'CO',pulse:{score:94,label:'Exceptional day',factors:{snow:98,crowds:91,lift_lines:95,terrain:96,wind:72}},conditions:{temperature_f:12,feels_like_f:-4,snow_24h_in:9,wind:'W 18 mph',terrain_open_pct:88},crowds:{level:'low',trend:'steady',contributors:964},lifts:[{name:'Lenawee Express',area:'Upper mountain',status:'open',wait_minutes:2,trend:'decreasing'},{name:'Black Mountain',area:'Base area',status:'open',wait_minutes:13,trend:'increasing'},{name:'Beavers',area:'West side',status:'open',wait_minutes:4,trend:'steady'},{name:'Pali',area:'Front side',status:'open',wait_minutes:6,trend:'steady'},{name:'Molly Hogan',area:'Learning area',status:'closed',wait_minutes:null,trend:'resort update 6m ago'}],runs:[{name:'The Beavers',difficulty:'Expert',status:'open',surface:'powder'},{name:'Steep Gullies',difficulty:'Extreme',status:'open',surface:'patrol gate'},{name:'East Wall',difficulty:'Extreme',status:'caution',surface:'hike access'},{name:'Molly Hogan',difficulty:'Learning area',status:'closed',surface:'operations hold'}]},
    loveland:{id:'loveland',name:'Loveland Ski Area',state:'CO',pulse:{score:91,label:'Powder window open',factors:{snow:97,crowds:94,lift_lines:93,terrain:88,wind:61}},conditions:{temperature_f:9,feels_like_f:-8,snow_24h_in:11,wind:'W 23 mph',terrain_open_pct:84},crowds:{level:'low',trend:'steady',contributors:718},lifts:[{name:'Lift 4',area:'Upper basin',status:'open',wait_minutes:2,trend:'steady'},{name:'Ptarmigan',area:'Upper mountain',status:'open',wait_minutes:4,trend:'decreasing'},{name:'Chet’s Dream',area:'Valley',status:'open',wait_minutes:7,trend:'increasing'},{name:'Lift 9',area:'Continental Divide',status:'hold',wait_minutes:null,trend:'gusts 38 mph'},{name:'Lift 2',area:'North side',status:'closed',wait_minutes:null,trend:'resort update 4m ago'}],runs:[{name:'The Ridge',difficulty:'Expert',status:'open',surface:'wind refill'},{name:'Rock Chutes',difficulty:'Expert',status:'open',surface:'deep snow'},{name:'Cat’s Meow',difficulty:'Black',status:'caution',surface:'wind affected'},{name:'Chair 2 terrain',difficulty:'Mixed',status:'closed',surface:'operations hold'}]},
    winter:{id:'winter',name:'Winter Park',state:'CO',pulse:{score:79,label:'Very good right now',factors:{snow:81,crowds:69,lift_lines:73,terrain:94,wind:88}},conditions:{temperature_f:16,feels_like_f:7,snow_24h_in:5,wind:'NW 9 mph',terrain_open_pct:96},crowds:{level:'busy',trend:'increasing at base',contributors:1532},lifts:[{name:'Panoramic',area:'Parsenn Bowl',status:'open',wait_minutes:9,trend:'decreasing'},{name:'Super Gauge',area:'Mary Jane',status:'open',wait_minutes:12,trend:'increasing'},{name:'Eagle Wind',area:'Vasquez Cirque',status:'open',wait_minutes:3,trend:'steady'},{name:'Gondola',area:'Winter Park base',status:'open',wait_minutes:16,trend:'increasing'},{name:'Looking Glass',area:'Discovery Park',status:'closed',wait_minutes:null,trend:'resort update 12m ago'}],runs:[{name:'Pano Trees',difficulty:'Expert',status:'open',surface:'soft snow'},{name:'Eagle Wind',difficulty:'Expert',status:'open',surface:'natural snow'},{name:'Village Way',difficulty:'Green',status:'caution',surface:'congested'},{name:'Looking Glass terrain',difficulty:'Learning area',status:'closed',surface:'operations hold'}]},
    eldora:{id:'eldora',name:'Eldora Mountain',state:'CO',pulse:{score:74,label:'Good and improving',factors:{snow:72,crowds:78,lift_lines:82,terrain:76,wind:67}},conditions:{temperature_f:21,feels_like_f:12,snow_24h_in:3,wind:'NW 14 mph',terrain_open_pct:91},crowds:{level:'moderate',trend:'decreasing',contributors:486},lifts:[{name:'Alpenglow',area:'Front side',status:'open',wait_minutes:3,trend:'decreasing'},{name:'Corona',area:'West side',status:'open',wait_minutes:5,trend:'steady'},{name:'Indian Peaks',area:'Central',status:'open',wait_minutes:14,trend:'maintenance queue'},{name:'Caribou',area:'Learning area',status:'open',wait_minutes:6,trend:'steady'},{name:'Challenge',area:'Race arena',status:'closed',wait_minutes:null,trend:'resort update 10m ago'}],runs:[{name:'Salto Glades',difficulty:'Expert',status:'open',surface:'soft pockets'},{name:'Corona Bowl',difficulty:'Black',status:'open',surface:'wind buff'},{name:'West Ridge',difficulty:'Black',status:'caution',surface:'thin coverage'},{name:'Challenge course',difficulty:'Race closure',status:'closed',surface:'race closure'}]}
  };

  function toUiOperations(resort){
    const waitLevel=minutes=>minutes===null?'high':minutes>=15?'high':minutes>=8?'med':'low';
    return {
      count:`${resort.lifts.filter(lift=>lift.status==='open').length}/${resort.lifts.length} shown open`,
      lifts:resort.lifts.map(lift=>[lift.name,lift.area,lift.status==='closed'?'Closed':lift.status==='hold'?'Wind hold':`${lift.wait_minutes} min`,lift.trend,waitLevel(lift.wait_minutes)]),
      runs:resort.runs.map(run=>[run.name,`${run.difficulty} · ${run.surface}`,run.status==='open'?'Open':run.status==='caution'?'Caution':'Closed',run.status==='caution'?'warning':run.status])
    };
  }

  return {resorts,sourceMeta,toUiOperations};
});
